### ISSUE TITLE
Transaction ID: 48dafbc531ef0d09c55b5eeeb71b2c2d547cb066d058a5018d43ec1578b3fc4

### ISSUE THREAD

**Issue by manzini08** [CoinSpace/CoinSpace#12]
This transaction seems to be stuck in processing. Not seeing any confirmations. Help please. 

Transaction ID: 48dafbc531ef0d09c55b5eeeb71b2c2d547cb066d058a5018d43ec1578b3fc4

Transaction Fee: .0000226

Inputs: 
1BSub6GNDHS17CwzRGP5FTeb5jUZpQuiJT
0.0348535

Outputs:
1HKySzb3HqBNYhRDZrWVbTNGByxUtKPuRd
1357jqVDkzTyHHVZTTjUXYErFuqDEaLHZc 0.0348
0.0000309

**Comment by nikashitsa** [comment]
Could you please attach screenshot? Because I don't see your transaction in public blockchain explorers.

**Comment by manzini08** [comment]
![screenshot_20171209-044310](https://user-images.githubusercontent.com/34379523/33794535-fca22962-dc9b-11e7-8179-bb77cc495e58.png)
![screenshot_20171209-044333](https://user-images.githubusercontent.com/34379523/33794536-029c2070-dc9c-11e7-9b62-f6818a5ea28d.png)
![screenshot_20171209-044346](https://user-images.githubusercontent.com/34379523/33794538-073cc65c-dc9c-11e7-8f0d-96fa80b0fceb.png)

**Comment by iwonapiasecka** [comment]
09.12.2017 09:06 "nikashitsa" <notifications@github.com> napisał(a):

**Comment by nikashitsa** [comment]
Your transaction is still pending.  
Looks like you used minimal fee. Now bitcoin network is high loaded so it might take long time to get confirmation. Please, track your transactions status here https://blockchain.info/tx/48dafbcb531ef0d09c55b5eeeb71b2c2d547cb066d058a5018d43ec1578b3fc4

**Comment by manzini08** [comment]
Any way to cancel the transaction or push it back thru with a higher fee?

**Comment by nikashitsa** [comment]
Looks like your transaction is missing from our bitcoin node now (it was restarted 4 hours ago for some reason). So, it should be missing from your wallet transaction list, right? Try to create this transaction again with higher fee. This becomes more likely to be mined and will get included in the blockchain - invalidating the slower-to-confirm original.

**Comment by manzini08** [comment]
Okay thanks. I just created a new transaction with the default fee.

**Comment by manzini08** [comment]
The transaction completed. Thanks for your help Sir.
