### ISSUE TITLE
Add .ipa & .apk files to github releases

### ISSUE THREAD

**Issue by emanuelb** [CoinSpace/CoinSpace#47]
Add .ipa file (ios app) & universal .apk (android app) to the releases at github:
https://github.com/CoinSpace/CoinSpace/releases/
which currently have assets for other OS (windows, etc...) but not for mobile.

**Comment by nikashitsa** [comment]
.apk file added here https://github.com/CoinSpace/CoinSpace/releases/tag/v6.6.0.
.ipa file will not be added (no reasons).
