### ISSUE TITLE
Cannot install monero-core-js for Web project

### ISSUE THREAD

**Issue by Jobcrazy** [CoinSpace/CoinSpace#56]
$ npm install
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@CoinSpace/monero-core-js/0.2.0/35f5c003360d4ea3cabc3c464591b8081f160e3e - authentication token not provided

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LiuHang\AppData\Local\npm-cache\_logs\2023-12-01T05_06_22_835Z-debug-0.log

**Comment by nikashitsa** [comment]
It's a github package.

> You must use a personal access token (classic) with the appropriate scopes to publish and install packages in GitHub Packages

More info here: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-with-a-personal-access-token

**Comment by Jobcrazy** [comment]
> It's a github package.
> 
> > You must use a personal access token (classic) with the appropriate scopes to publish and install packages in GitHub Packages
> 
> More info here: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-with-a-personal-access-token

Thank you so much! I didn't know this before. Sorry to trouble you.
