### ISSUE TITLE
Unable to send crypto "Error! Please try again later."

### ISSUE THREAD

**Issue by freebiesoft** [CoinSpace/CoinSpace#62]
After I have typed in the address and amount I get to this screen and I type the pin in correctly (same one I used to authenticate into the app in the first place), and I get this:

![image](https://github.com/CoinSpace/CoinSpace/assets/28921401/5686c82f-b304-4850-8120-8ffc8c2aa857)

I am using Snap app on Ubuntu 23.10

**Comment by nikashitsa** [comment]
Please contact support@coin.space and specify version of you app and what crypto you are trying to send.
