### ISSUE TITLE
no AppleSilicon version available anymore

### ISSUE THREAD

**Issue by core-code** [CoinSpace/CoinSpace#63]
6.4.0 had a macOS ARM version. 6.4.2 doesn't - both the ZIP and the DMG are intel-only. any reason?

**Comment by mahnunchik** [comment]
There was no support AppleSilicon in 6.4.0 https://github.com/CoinSpace/CoinSpace/releases/tag/v6.4.0

macOS app are seamlessly converted on the fly from Intel arch. This is a compromise to avoid doubling the size of the application.

**Comment by core-code** [comment]
the DMG download definitely was Apple Silicon:
<img width="534" alt="Screenshot 2024-07-03 at 14 40 41" src="https://github.com/CoinSpace/CoinSpace/assets/1261954/dc8f6a95-4a2c-428e-8489-bc837a036c4b">

**Comment by mahnunchik** [comment]
Yes, only in 6.4.0 version it was build for arm architecture by mistake. Versions before and after are build for Intel.

**Comment by core-code** [comment]
ok thanks, if you don't plan on offering a native version again lets close this
