### ISSUE TITLE
can't open wallet

### ISSUE THREAD

**Issue by chenzhitong** [CoinSpace/CoinSpace#8]
![image](https://user-images.githubusercontent.com/6295602/30306201-7220f6ba-97a9-11e7-9570-c2653eba5c8d.png)
I can't open my wallet, my address is 1Fth1nAYLDGojvH8EXBiM58PFeJHGrskV2

**Comment by chenzhitong** [comment]
已经解决了，多试了几次就好使了。

**Comment by jspeigner** [comment]
Are you still seeing this issue?

**Comment by chenzhitong** [comment]
The problem has been solved.
